"""empty message

Revision ID: 7d38235a0334
Revises: 4b894de48697
Create Date: 2020-10-21 19:39:52.582687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d38235a0334'
down_revision = '4b894de48697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.String(), nullable=True))
    op.execute("Update shows set start_time='2020-10-20' where start_time is null;")
    op.alter_column('shows', "start_time", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
